[workspace]
resolver = "3"
members = ["game"]

[workspace.dependencies]
mplk_grid = { path = "./grid" }
mplk_transform = { path = "./transform" }

# 2D
bevy = { version = "0.19", default-features = false, features = [
  "2d",
  "ui",
  "audio",
  "dev",
] }
derive_more = { version = "2.1.1", features = ["std", "error", "display"] }
pathfinding = "4.15.0"
rand = "0.9"
tiny_bail = "0.7.0"
# Compile out low-severity logs to improve performance.
# Remove these features if you want to profile your game with tracy.
# (see <https://github.com/bevyengine/bevy/blob/main/docs/profiling.md#tracy-profiler>)
tracing = { version = "0.1", features = [
  "max_level_debug",
  "release_max_level_warn",
] }
mplk_tween = { git = "https://github.com/meepleek/mplk_bevy_toolkit.git", tag = "v0.19.0" }
mplk_ext = { git = "https://github.com/meepleek/mplk_bevy_toolkit.git", tag = "v0.19.0" }
mplk_utils = { git = "https://github.com/meepleek/mplk_bevy_toolkit.git", tag = "v0.19.0" }
bevy_asset_loader = { version = "0.27.0", features = ["2d"] }
itertools = "0.14.0"
bevy_trauma_shake = { git = "https://github.com/meepleek/bevy_trauma_shake", version = "0.8.0" }
strum = { version = "0.28.0", features = ["derive"] }
ansi_term = "0.12.1"
test-case = "3.3.1"
pretty_assertions = "1.4.1"
tracing-test = "0.2.6"

[workspace.lints.clippy]
# Bevy supplies arguments to systems via dependency injection, so it's natural for systems to
# request more than 7 arguments, which would undesirably trigger this lint.
too_many_arguments = "allow"
# Queries may access many components, which would undesirably trigger this lint.
type_complexity = "allow"
# Make sure macros use their standard braces, such as `[]` for `bevy_ecs::children!`.
nonstandard_macro_braces = "warn"


# Enable a small amount of optimization in the dev profile.
[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[profile.release]
# Compile the entire crate as one unit.
# Slows compile times, marginal improvements.
codegen-units = 1
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"

# This profile will be used by `bevy run web` automatically.
[profile.web-release]
# Default to release profile values.
inherits = "release"
# Optimize with size in mind (also try "z", sometimes it is better).
# Slightly slows compile times, great improvements to file size and runtime performance.
opt-level = "s"
# Strip all debugging information from the binary to slightly reduce file size.
strip = "debuginfo"

# Optimize for build time in CI.
[profile.ci]
inherits = "dev"
opt-level = 0
debug = "line-tables-only"
codegen-units = 4

[profile.ci.package."*"]
opt-level = 0
